# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

sass:
    sass_dir: assets/sass
    style: compressed

# UI configs
title: "Alright My Lover"
subtitle: "See the world through my eyes!"
author: "Materialiser Ltd"
header:
 title: "Alright My Lover"
 subtitle: ""
footer:
 name: "Alright my lover!"
 bio: "<p>My name is Leo and here are some of my snaps! <br/>I am a software developer and a geek that just moved to Bristol.</p>"

social_urls:
 facebook: "https://facebook.com/leoseccia"
 twitter: "https://www.twitter.com/leoseccia"
 instagram: "https://www.instagram.com/leoseccia"
 #dribbble: "https://dribbble.com/rampatra"
 linkedin: "https://in.linkedin.com/in/leoseccia"
 github: "https://www.github.com/leoseccia"
