# Base configs
baseurl: "https://cedward.photos"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-131906452-1"

# UI configs
title: "Photography by Charles Edward Thrash"
subtitle: "Birdwatcher"
author: "Charles Edward Thrash"
header:
 title: "Photography"
 subtitle: "by Charles Edward"
footer:
 name: "Hey there, my name is Charles"
 bio: "I am a bird and nature photographer based in the Pacific Northwest region."
