# Base configs
baseurl: "jasonschneider.net"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-128022708-1"

# UI configs
title: "Photography by Jason Schneider"
subtitle: "A Collection of Permanent Observations"
author: "Jason Schneider"
header:
 title: "Jason Schneider"
 subtitle: "photography"
footer:
 name: "Jason Schneider"
 bio: "I am a multi-faceted creator of dynamic and cathartic content across a wide spectrum of media formats.: My resume is best viewed Just <a href=\"https://schnjaso2.github.io/jps.github.io/">as a map.</a> ;)"
web_design: "jps"
social_urls:
  facebook: "https://www.facebook.com/permanentobserver"
 
  instagram: "https://www.instagram.com/permanentobserver"
  
  linkedin: "https://www.linkedin.com/in/prmntobsrvr/"
  github: "https://www.github.com/schnjaso2"
  soundcloud: "https://soundcloud.com/kid-chivalrous"
  