# Base configs
baseurl: "http://bastianphoto.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Kim Bastian"
subtitle: "See the world through my eyes!"
author: "Kim Bastian"
header:
 title: "Photography"
 subtitle: "by Kim Bastian"
footer:
 name: "Hey there, my name is Kim Bastian"
 bio: "I'm an amateur photographer based in Copenhagen. Photography is my hobby and I take photos of whatever I find interesting - especially street photography, architecture, travel photography and portraits. I work as a civil engineer and in my spare time in enjoying photography. If you are interested in having your headshot taken, real estate photos or any other project, feel free to contact me."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/kim.bastian"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/kim.bastian"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/kimbastiancivil"
  github: "https://www.github.com/rampatra"
