# Base configs
baseurl: "http://roman-photo.kalimero.rocks"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Roman-photo"
subtitle: "Yet anoother Kalimero Art Gallery "
author: "KalimeroX1/9"
header:
 title: "Roman-photo"
 subtitle: "by Kalimero"
footer:
 name: "Hey there, my name Kalimero"
 bio: "I’ve been a Wild at Art ComixMaker since 1999"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/kalimero_666_"
  instagram: "https://www.instagram.com/kalimero_666"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/"
  github: "https://www.github.com/kalimerO666"


