# Base configs
baseurl: "https://nextchaptermy.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Next Chapter Studio"
subtitle: "See the world through my eyes!"
author: "Next Chapter Studio"
header:
 title: "Photography"
 subtitle: "by Next Chapter Studio"
footer:
 name: "About Us"
 bio: "Next Chapter Studio is a Kuala Lumpur, Malaysia based photographic studio specialising in the creation of timeless commercial product photography, corporate and business profile headshots, event photography and also wedding photography. We are a team of professionals dedicated to create photographic masterpieces and we pursue perfection. Our aim is to surpass all of your expectations while providing you with an amazing and unforgettable experience. ​ Through our unique photographic techniques and cutting edge digital retouching technologies, we have worked with world brand leaders such as Ferrari, Mercedes Benz, Nike, Spritzer, Nestle and etc."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/nextchaptermy"
  instagram: "https://www.instagram.com/nextchapter_my"
