# Base configs
baseurl: "mmelrayah.github.io/futlens-photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Future Lens"
subtitle: "See the world through our eyes!"
author: "Anas Dawood"
header:
 title: "Futlens"
 subtitle: "by Anas Dawod"
footer:
 name: "Hi There.."
 bio: "When creativity and technology delivered at one."
 github: "Want a magnificent photo session, event or you you think we are doing a great work here ? contact us ;)"
web_design: "MME"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/futlens"
  instagram: "https://www.instagram.com/futlens"
  dribbble: "https://dribbble.com/futlens"
  linkedin: "https://in.linkedin.com/in/mmelrayah"
  github: "https://www.github.com/mmelrayah.github.io/futlens-photography.github.io/"
